steps:
  # Step 1: Run tests
  - name: 'golang:1.24-alpine'
    id: 'run-tests'
    dir: 'summary-service'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache git gcc musl-dev
        go mod download
        go test -v ./...

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    dir: 'summary-service'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/summary-service:manual-v1'
      # - '-t'
      # - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/summary-service:$SHORT_SHA'
      # - '-t'
      # - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/summary-service:latest'
      - '.'

  # Step 3: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      # - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/summary-service:manual-v1'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'services'
      - 'replace'
      - 'cloudrun/summary-service.yaml' # Path to the config file
      - '--region'
      - 'us-central1' # e.g., us-central1
      - '--project'
      - '$PROJECT_ID'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/summary-service:manual-v1'
  # - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/summary-service:$SHORT_SHA'
  # - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/summary-service:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

substitutions:
  _REPO_NAME: "prod-planner-repo"