FROM golang:1.21-alpine

WORKDIR /app
COPY trend-jobs/weekly/go.mod trend-jobs/weekly/go.sum ./
RUN go mod download

COPY trend-jobs/weekly .

RUN go build -o weekly-job .

# Copy crontab
COPY crontab.weekly /etc/crontabs/root

CMD ["crond", "-f", "-l", "2"]
