services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=productivity_planner
      - POSTGRES_USER=adityasawant
      - POSTGRES_PASSWORD=S10dulkar
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "adityasawant"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      # - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
        - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./user-service/.env
    networks:
      - backend

  session-service:
    build: ./session-service
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./session-service/.env
    networks:
      - backend

  summary-service:
    build: ./summary-service
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./summary-service/.env
    networks:
      - backend
    
  trend-service:
    build: ./trend-service
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./trend-service/.env
    networks:
      - backend

  notification-service:
    build: ./notification-service
    ports:
      - "8087:8087"
    depends_on:
      - pubsub-emulator
    env_file:
      - ./notification-service/.env
    environment:
      profile=local
      PORT=8087
      PROJECT_ID=systemic-productivity-planner
      PUB_SUB_DAILY_TOPIC=daily_trend_topic
      PUB_SUB_WEEKLY_TOPIC=weekly_trend_topic
      PUB_SUB_DAILY_SUBSCRIPTION=daily_trend_sub
      PUB_SUB_WEEKLY_SUBSCRIPTION=weekly_trend_sub
    networks:
      - backend

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    # depends_on:
    #   - session-service
    #   - user-service
    #   - summary-service
    env_file:
      - ./gateway/.env
    networks:
      - backend
  
  daily-trend-job:
    build:
      context: ./daily-trend-analysis-worker    
    env_file:
      - ./daily-trend-analysis-worker/.env
    depends_on:
      - postgres
      - pubsub-emulator
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
    networks:
      - backend

  weekly-trend-job:
    build:
      context: ./weekly-trend-analysis-worker
    env_file:
      - ./weekly-trend-analysis-worker/.env
    depends_on:
      - postgres
      - pubsub-emulator
    networks:
      - backend

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=systemic-productivity-planner --host-port=0.0.0.0:8085
    ports:
      - "8086:8085"
    networks:
      - backend
      
volumes:
  pgdata:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ./pgdata
  
networks:
  backend: