name: Build and Test

on:
    push:
        branches: [master]
        paths: ./user-service
    pull_request:
        branches: [master]

env:
    GO_VERSION: '1.23'
    NODE_VERSION: '20'

jobs:
    user_service:
        name: Build & Test User Service
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: ${{env.GO_VERSION}}

            - name: Run Go unit tests
              run: |               
                cd user-service
                go mod tidy
                go test ./...
                cd ..
                
            
            - name: Build Go services
              run: |
                cd user-service
                go build -o $dir ./cmd
                cd ..
